### ISSUE TITLE
Plugins are deleting after update

### ISSUE THREAD

**Issue by uqlel** [SuchByte/Macro-Deck#59] opened 2021-11-11 07:58 UTC
**Describe the bug**
Every time the macro deck updates (I can't cancel the update) I lose all my plugins, and I have to configure all macros, and it's boring doing it once a day. Also, it randomly stops working. Like it's bugging on this menu
![obraz](https://user-images.githubusercontent.com/59146379/141259993-dc258428-7efe-4e0d-bf08-338d80e4b5db.png)
And macros are working but I can't launch GUI.

**To Reproduce**
1. Launch Macro Deck
2. It will update
3. Now you haven't any plugins

**Expected behavior**
Plugins will be there

**Screenshots**
![obraz](https://user-images.githubusercontent.com/59146379/141259745-0fb84dde-33b8-482c-b1cb-5f2d071f1b3f.png)

**Additional context**
Also, it randomly stops working. Like it's bugging on this menu
![obraz](https://user-images.githubusercontent.com/59146379/141259993-dc258428-7efe-4e0d-bf08-338d80e4b5db.png)
And macros are working but I can't launch GUI.

**Comment by SuchByte** [comment] 2021-11-12 17:41
I need more information about the problem with the plugins. Can you tell me from which version you updated when this happened?

Generally this is not possible because the plugins are stored in "%Appdata%\Macro Deck\plugins\" and the Macro Deck directory in Appdata gets not touched when upgrading Macro Deck. It happened once in the early dev versions (from version 2b12 to 2b13) where I made a big change. Please make sure you're not using some 3rd party clean up software, that deletes the Macro Deck directory after uninstalling while the update is running.


The issue with the freezing context menu is known but I found no solution or the problem that causes this issue.

**Comment by uqlel** [comment] 2021-11-12 18:37
> I need more information about the problem with the plugins. Can you tell me from which version you updated when this happened?
> 
> Generally this is not possible because the plugins are stored in "%Appdata%\Macro Deck\plugins" and the Macro Deck directory in Appdata gets not touched when upgrading Macro Deck. It happened once in the early dev versions (from version 2b12 to 2b13) where I made a big change. Please make sure you're not using some 3rd party clean up software, that deletes the Macro Deck directory after uninstalling while the update is running.
> 
> The issue with the freezing context menu is known but I found no solution or the problem that causes this issue.

i got like 4 updates and everytime the plugins are deleting themself

**Comment by SuchByte** [comment] 2021-11-12 18:45
> > I need more information about the problem with the plugins. Can you tell me from which version you updated when this happened?
> > Generally this is not possible because the plugins are stored in "%Appdata%\Macro Deck\plugins" and the Macro Deck directory in Appdata gets not touched when upgrading Macro Deck. It happened once in the early dev versions (from version 2b12 to 2b13) where I made a big change. Please make sure you're not using some 3rd party clean up software, that deletes the Macro Deck directory after uninstalling while the update is running.
> > The issue with the freezing context menu is known but I found no solution or the problem that causes this issue.
> 
> i got like 4 updates and everytime the plugins are deleting themself

Updates of the plugins or of Macro Deck?

On which version are you now?

**Comment by SuchByte** [comment] 2021-11-14 20:09
I'm closing this because as I said, your described issue is not caused by Macro Deck. The entire "%Appdata%\Macro Deck\" directory gets not touched by the installer.

The freeze of the context menu and the entire GUI is fixed in version 2.3.1-beta and 2.3.2-dev.

**Closed by SuchByte** 2021-11-14 20:09 UTC
Labels: bug
