### ISSUE TITLE
Application UI freeze

### ISSUE THREAD

**Issue by zedalert** [SuchByte/Macro-Deck#61] opened 2021-11-12 22:41 UTC
It could happen in various situations: when you setup your macros or just perform navigation inside settings/tree. It also could unfreeze by itself after several minutes, but not so often. At the same time the web UI is working as expected, the system tray menu will only popup once and also freeze.

Tried 2.1.2-beta and 2.2.0-dev - same behaviour.
OS: Windows 11 21H2

1. Open configure UI
2. Click on add/edit macro or navigate inside tree
3. Repeat until UI froze

**Comment by SuchByte** [comment] 2021-11-13 01:25
Please try with version 2.2.1-dev. I made a few changes to access this issue because I don't really know what causes this issue.

**Comment by zedalert** [comment] 2021-11-13 15:16
Yes, 2.2.1-dev is much better, I froze it only once during the whole day when I was trying to open it up from the system tray. Still don't see any dependence on how to get it 100% frozen.

Maybe there is an option to enable application debug log or I can view somewhere .NET log?

**Comment by SuchByte** [comment] 2021-11-13 17:18
Well I made another change in 2.3.0-beta as I now think that the freeze and slowdown is caused by the AutomationFocusChangedEventHandler out of System.Windows.Automation. Now I directly use the WinEventHook and maybe it's fixed now.

There's currently no option for logs other than starting Macro Deck with an debugger attached.

**Comment by zedalert** [comment] 2021-11-14 16:18
So far so good, 2.3.2-dev is stable for more than one day, looks like UI freeze gone.

**Closed** 2021-11-14 18:39 UTC
Labels: bug
